"""The scene compiler — a declared spec becomes HTML the app wrote.

The trust boundary of this whole app lives in this file. A narrator describes what
a scene should show; it never supplies markup. Everything below follows from that:

* **Element kinds are a closed set.** The narrator picks from templates; it cannot
  name a tag. An unknown (or otherwise malformed) element is DROPPED rather than
  aborting the whole scene — a legible partial beats a blank frame — and its loss
  is recorded (see ``scene_warnings``) so the narrator can be told. Dropping is
  safe precisely because a dropped element emits no markup: the closed set still
  means the compiler never turns a name it does not know into a tag.
* **Whole-spec gates stay hard.** The markup ban (``html``/``script``/…), the byte
  ceiling, and a spec with no elements at all still refuse outright: those are the
  trust boundary, not a per-element legibility nicety.
* **Every narrator string is escaped as text.** Narrator bytes reach the DOM only
  as content, never as markup or as script.
* **The one script is a constant.** It is emitted byte-identically and carries no
  interpolation. That is what makes ``script-src 'unsafe-inline'`` defensible: the
  inline script is the app's, and a test asserts the constant is what ships.
* **The CSP meta precedes every generated byte.** A policy that arrives after the
  content it governs has already lost.
* **``bind`` paths are resolved here, against run state.** A widget showing a
  number the panels disagree with is worse than no widget, and resolving in the
  page would put a second reader of state next to the first.

What the CSP allows, and why each entry is the narrowest form that still works:
``default-src 'none'`` (nothing loads), ``script-src 'unsafe-inline'`` (the app's
own constant, so a click can reach the parent), ``style-src 'unsafe-inline'`` (one
inline sheet), ``img-src data:`` (inline only — no network fetch dressed as an
image), ``connect-src 'none'`` (no exfiltration path at all), ``form-action
'none'`` and ``base-uri 'none'`` (no navigation-shaped escape).
"""

from __future__ import annotations

import hashlib
import html
import json
import os
import re
from pathlib import Path
from typing import Any

from view import strip_terminal_framing

#: Bumped when the compiled shape changes in a way a cached file cannot satisfy.
COMPILER = 1

#: A spec is a description, not a document. Anything past this is a narrator
#: trying to write a page.
MAX_SPEC_BYTES = 24_000
MAX_ELEMENTS = 60
MAX_TEXT = 400
MAX_ROWS = 40
MAX_COLUMNS = 6
#: A grid cell's `mark` glyph, in codepoints. Wide enough for a real emoji with a
#: variation selector or a keycap sequence, narrow enough that a sentence is not one:
#: a mark is a symbol, and a longer string is a `note` wearing the wrong field.
MAX_MARK = 4
#: A relationship graph's ceilings. Nodes are laid out by the backend on a ring,
#: so past a couple dozen the labels overlap and it stops being readable — the cap
#: is a legibility bound, not only a safety one.
MAX_NODES = 24
MAX_EDGES = 60
#: How deep a tree may nest before it is refused as either a cycle or unreadable.
MAX_TREE_DEPTH = 12

#: The closed set. A kind absent here is refused, never skipped.
ELEMENT_KINDS: frozenset[str] = frozenset(
    {
        "heading",
        "text",
        "note",
        "stat",
        "bar",
        "keyvalue",
        "list",
        "table",
        "choice",
        "divider",
        # Spatial / relational kinds. The narrator declares STRUCTURE (cells,
        # nodes, edges, parents) and never geometry — every coordinate below is
        # computed here, so a scene map cannot smuggle markup or a layout exploit.
        "grid",
        "links",
        "tree",
    }
)

_ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,63}$")
_PATH_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*$")


class SceneSpecError(ValueError):
    """A spec that cannot become a scene. Names the field so the narrator can fix
    the one thing that was wrong."""

    def __init__(self, field: str, expected: str) -> None:
        super().__init__(f"{field}: {expected}")
        self.field = field
        self.expected = expected


# ── the policy, and the one script ──────────────────────────────────────

CSP = (
    "default-src 'none'; "
    "script-src 'unsafe-inline'; "
    "style-src 'unsafe-inline'; "
    "img-src data:; "
    "connect-src 'none'; "
    "form-action 'none'; "
    "base-uri 'none'"
)

#: Emitted byte-identically, every time, with nothing interpolated into it. A
#: test asserts that: the moment narrator text could reach script context, the
#: escaping above stops being the boundary it claims to be.
#:
#: It reads a choice's id from a data attribute rather than from generated code,
#: and posts it to the parent. It also reports the document's own content height,
#: which is the only way the host can size the frame to the picture: the frame has
#: an opaque origin, so the parent cannot measure inside it. The parent side is the
#: app's own frame host.
SCENE_SCRIPT = """<script>
(function () {
  function envelope(extra) {
    extra.source = 'endless-scene';
    extra.sceneId = document.documentElement.dataset.scene || '';
    extra.nonce = document.documentElement.dataset.nonce || '';
    return extra;
  }
  document.addEventListener('click', function (e) {
    var el = e.target.closest('[data-choice]');
    if (!el) return;
    parent.postMessage(envelope({ choice: el.dataset.choice }), '*');
  });
  var last = 0;
  function report() {
    /* The CONTENT's own extent, not the body box: a body inflated to the frame's
       viewport reports its own height back and the frame can then never shrink.
       A child's own bottom margin counts -- it is part of what the picture
       occupies, and leaving it out cropped the last row by exactly that much.
       Block comments, not line ones: the document may not contain a double slash
       anywhere, which is what keeps a protocol-relative URL out of it. */
    var b = document.body, top = b.getBoundingClientRect().top, far = 0, i, el;
    for (i = 0; i < b.children.length; i++) {
      el = b.children[i];
      far = Math.max(far, el.getBoundingClientRect().bottom - top
        + (parseFloat(getComputedStyle(el).marginBottom) || 0));
    }
    var h = Math.ceil(far + (parseFloat(getComputedStyle(b).paddingBottom) || 0));
    if (!h || h === last) return;
    last = h;
    parent.postMessage(envelope({ height: h }), '*');
  }
  report();
  window.addEventListener('load', report);
  if (window.ResizeObserver) new ResizeObserver(report).observe(document.body);
})();
</script>"""

_STYLE = """<style>
:root { color-scheme: dark light; }
/* On the canvas as well as the body: a document shorter than its frame leaves the
   rest of the frame painted by the CANVAS, and an unpainted canvas shows the host
   page through it — which is how a scene came to sit on a pale slab under a light
   dashboard theme. */
html { background: #0b0c10; }
body {
  margin: 0; padding: 12px;
  font: 13px/1.6 system-ui, -apple-system, "Segoe UI", sans-serif;
  color: #e2e8f0; background: #0b0c10;
}
h3 { margin: 0 0 8px; font-size: 15px; font-weight: 600; }
.r { display: flex; gap: 10px; padding: 4px 0; align-items: baseline; }
.k { color: #6b7280; flex: 0 0 6em; }
.v { flex: 1; min-width: 0; overflow-wrap: anywhere; }
.n { color: #6b7280; }
.t { border-radius: 2px; height: 4px; background: #2d2f3d; margin-top: 5px; }
.f { height: 100%; background: #7c3aed; }
ul { margin: 6px 0; padding-left: 1.3em; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 4px 6px; border-bottom: 1px solid #2d2f3d; }
th { color: #6b7280; font-weight: 500; }
hr { border: none; border-top: 1px solid #2d2f3d; margin: 10px 0; }
button {
  display: block; width: 100%; text-align: left; margin: 6px 0;
  padding: 10px 12px; min-height: 44px;
  font: inherit; color: inherit; cursor: pointer;
  background: #1f2030; border: 1px solid #2d2f3d; border-radius: 8px;
}
/* Rows are sized by what is IN them and never by the room around them. Two
   independent latches, because what hands this box a height larger than its rows on
   a phone is not reproducible off-device: `align-content` otherwise defaults to
   stretch and shares any surplus out among the auto rows, and `grid-auto-rows` pins
   each track to its content even if something still does. Measured: a grid box
   forced to 464px turned six short labels into 236px boxes holding 57px of text,
   which is the shape a real phone showed; with these, 95px and 82px.
   Cells still stretch to their own row, so a row's boxes stay equal height. */
.grid {
  display: grid; gap: 6px; margin: 8px 0;
  align-content: start; grid-auto-rows: min-content;
}
/* A map cell is a label, not prose: the body's reading line-height turns six short
   cells into a tall airy block, and at phone width a column is ~100px wide, so a
   name that does not break lands outside its own box. */
.gc {
  background: #1f2030; border: 1px solid #2d2f3d; border-radius: 6px;
  padding: 8px; min-height: 44px; font-size: 12px; box-sizing: border-box;
  line-height: 1.3; min-width: 0; overflow-wrap: anywhere;
}
.gc.gm { border-color: #7c3aed; background: #241d3a; }
/* The cell's own symbol, inline before its name so it rides the label's first line
   and cannot be orphaned by a wrap. */
.gmk { margin-inline-end: 4px; font-size: 13px; }
.gn { display: block; color: #6b7280; font-size: 11px; line-height: 1.3; margin-top: 3px; }
.lkwrap { margin: 8px 0; }
svg.lk { width: 100%; height: auto; display: block; }
.lke { stroke: #2d2f3d; stroke-width: 1.2; }
.lkl { fill: #6b7280; font-size: 9px; text-anchor: middle; }
.lkn { fill: #7c3aed; }
.lknt { fill: #e2e8f0; font-size: 10px; text-anchor: middle; }
ul.tree, ul.tree ul { list-style: none; margin: 4px 0; padding-left: 14px; border-left: 1px solid #2d2f3d; }
ul.tree li { padding: 3px 0; }
.tn { color: #6b7280; font-size: 11px; }
</style>"""


# ── binding ──────────────────────────────────────────────────────────────


def resolve_bind(path: str, state: dict[str, Any]) -> Any:
    """Read a dotted path out of run state, or raise.

    Still raises on an unresolvable path — but the caller (``_valued``) now catches
    that and falls back to the element's literal ``value``/``text``, dropping the
    element only when there is no literal either. A malformed PATH (not a typo'd
    one, but a shape that could walk into internals) is refused here regardless.
    """
    if not isinstance(path, str) or not _PATH_RE.match(path):
        raise SceneSpecError("bind", f"a dotted path, got {path!r}")
    node: Any = state
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            raise SceneSpecError("bind", f"nothing at {path!r}")
        node = node[part]
    return node


# ── compiling ────────────────────────────────────────────────────────────


def _text(value: Any, field: str, *, cap: int = MAX_TEXT) -> str:
    """Coerce a scalar to display text, truncating rather than refusing.

    A legible partial beats a blank frame: an over-long string is cut to the cap
    with an ellipsis, and an unexpected scalar (bool, etc.) is stringified. Only a
    genuinely unrenderable container (dict/list) is refused, so the ONE element
    carrying it is dropped by the salvage loop instead of the whole scene.
    """
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        raise SceneSpecError(field, "text")
    out = str(value)
    if len(out) > cap:
        out = out[: max(1, cap - 1)] + "…"
    return out


def _celltext(value: Any, field: str, *, cap: int = MAX_TEXT) -> str:
    """``_text`` that degrades a bad cell to empty rather than dropping its whole
    container — used where one broken cell should not cost the entire table/graph."""
    try:
        return _text(value, field, cap=cap)
    except SceneSpecError:
        return ""


def _valued(el: dict[str, Any], where: str, bound: Any, bind_failed: bool, key: str) -> Any:
    """The value a value-bearing element should show: the resolved bind if it
    resolved, else the element's literal. A bind that failed AND has no literal to
    fall back to raises, so the salvage loop drops just that element (item 5)."""
    if "bind" in el and not bind_failed:
        return bound
    literal = el.get(key)
    if bind_failed and literal is None:
        raise SceneSpecError(f"{where}.bind", "unresolved, and no literal fallback")
    return literal


def _esc(value: Any) -> str:
    """Every narrator string passes through here on its way to the DOM.

    Escaping AND framing removal, in that order, because a scene is a second
    route to the DOM and R18 applies to both. Reusing the prose stripper rather
    than writing a second one: two implementations of "what counts as framing"
    would drift, and the one in ``view`` is the one with the tests that prove it
    keeps the words inside a box.
    """
    return html.escape(strip_terminal_framing(str(value)), quote=True)


def _pct(value: Any, cap: Any) -> float | None:
    try:
        v, c = float(value), float(cap)
    except (TypeError, ValueError):
        return None
    if c <= 0:
        return None
    return max(0.0, min(1.0, v / c))


def _element(el: Any, index: int, state: dict[str, Any]) -> str:
    where = f"elements[{index}]"
    if not isinstance(el, dict):
        raise SceneSpecError(where, "an object")
    kind = el.get("kind")
    if kind not in ELEMENT_KINDS:
        raise SceneSpecError(f"{where}.kind", f"one of {sorted(ELEMENT_KINDS)}, got {kind!r}")

    # A bound value replaces `value`/`text`. An unresolvable bind is NOT fatal
    # here: it falls back to the element's literal, and drops only this element
    # (via the salvage loop) when there is no literal to fall back to.
    bound: Any = None
    bind_failed = False
    if "bind" in el:
        try:
            bound = resolve_bind(el["bind"], state)
        except SceneSpecError:
            bind_failed = True

    if kind == "divider":
        return "<hr>"

    if kind == "heading":
        return f"<h3>{_esc(_text(el.get('text'), f'{where}.text'))}</h3>"

    if kind in ("text", "note"):
        raw = _valued(el, where, bound, bind_failed, "text")
        body = _esc(_text(raw, f"{where}.text"))
        return f'<p class="n">{body}</p>' if kind == "note" else f"<p>{body}</p>"

    if kind == "keyvalue":
        label = _esc(_text(el.get("label"), f"{where}.label"))
        raw = _valued(el, where, bound, bind_failed, "value")
        value = _esc(_text(raw, f"{where}.value"))
        return f'<div class="r"><div class="k">{label}</div><div class="v">{value}</div></div>'

    if kind in ("stat", "bar"):
        label = _esc(_text(el.get("label"), f"{where}.label"))
        raw = _valued(el, where, bound, bind_failed, "value")
        value = _esc(_text(raw, f"{where}.value", cap=64))
        cap = el.get("max")
        pct = _pct(raw, cap) if cap is not None else None
        tail = (
            f'<span class="n"> / {_esc(_text(cap, f"{where}.max", cap=32))}</span>'
            if cap is not None
            else ""
        )
        bar = (
            f'<div class="t"><div class="f" style="width:{round(pct * 100)}%"></div></div>'
            if pct is not None
            else ""
        )
        return (
            f'<div class="r"><div class="k">{label}</div>'
            f'<div class="v">{value}{tail}{bar}</div></div>'
        )

    if kind == "list":
        items = el.get("items")
        if not isinstance(items, list):
            raise SceneSpecError(f"{where}.items", "an array")
        items = items[:MAX_ROWS]  # truncate rather than reject
        cells: Any = "".join(
            f"<li>{_esc(_celltext(i, f'{where}.items[{n}]'))}</li>" for n, i in enumerate(items)
        )
        return f"<ul>{cells}</ul>"

    if kind == "table":
        cols = el.get("columns")
        if not isinstance(cols, list) or not cols:
            raise SceneSpecError(f"{where}.columns", "a non-empty array")
        cols = cols[:MAX_COLUMNS]  # truncate wide headers
        rows = el.get("rows")
        rows = rows[:MAX_ROWS] if isinstance(rows, list) else []
        head = "".join(
            f"<th>{_esc(_celltext(c, f'{where}.columns[{n}]'))}</th>" for n, c in enumerate(cols)
        )
        body = ""
        for rn, row in enumerate(rows):
            if not isinstance(row, list):
                continue  # drop a non-array row, keep the table
            cells = list(row[: len(cols)])  # truncate a long row
            cells += [""] * (len(cols) - len(cells))  # pad a short row
            body += (
                "<tr>"
                + "".join(
                    f"<td>{_esc(_celltext(c, f'{where}.rows[{rn}][{cn}]'))}</td>"
                    for cn, c in enumerate(cells)
                )
                + "</tr>"
            )
        return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"

    if kind == "grid":
        cols = el.get("columns")
        if not isinstance(cols, int) or isinstance(cols, bool):
            cols = 1
        cols = max(1, min(8, cols))  # clamp into range rather than reject
        cells = el.get("cells")
        if not isinstance(cells, list) or not cells:
            raise SceneSpecError(f"{where}.cells", "a non-empty array")
        cells = cells[:MAX_ROWS]  # truncate rather than reject
        out = []
        for cn, c in enumerate(cells):
            if not isinstance(c, dict):
                continue  # drop a bad cell, keep the grid
            label = _esc(_celltext(c.get("label"), f"{where}.cells[{cn}].label", cap=64))
            note = c.get("note")
            nt = _esc(_celltext(note, f"{where}.cells[{cn}].note", cap=64))
            note_html = f'<span class="gn">{nt}</span>' if note not in (None, "") else ""
            # `mark` carries two different intentions and both are honoured, because
            # collapsing them loses information either way. A GLYPH (a string) is a
            # per-cell symbol and renders as a badge: it distinguishes cells from each
            # other, which is what a map needs. `true` is a whole-cell highlight and
            # tints the box. A glyph deliberately does NOT also tint: a narrator marks
            # every cell of a map with its own symbol, and tinting on any mark made all
            # six cells identically purple — a highlight that highlights everything
            # says nothing, and the symbols themselves were dropped on the floor.
            #
            # The glyph is escaped narrator TEXT, like a label or a note. `columns`
            # (a validated int) and the tint class remain the only non-narrator values
            # reaching markup, so no coordinate or class is ever author text.
            mark = c.get("mark")
            badge = ""
            tint = ""
            if isinstance(mark, str):
                glyph = mark.strip()
                # A mark is a symbol, not a sentence. Past the cap it is dropped
                # WHOLE rather than cut: an emoji is a codepoint sequence, and
                # truncating one renders a lone variation selector or joiner.
                if glyph and len(glyph) <= MAX_MARK:
                    badge = f'<span class="gmk">{_esc(glyph)}</span>'
            elif mark:
                tint = " gm"
            out.append(f'<div class="gc{tint}">{badge}{label}{note_html}</div>')
        return (
            f'<div class="grid" style="grid-template-columns:repeat({cols},1fr)">'
            + "".join(out)
            + "</div>"
        )

    if kind == "links":
        nodes = el.get("nodes")
        if not isinstance(nodes, list) or not nodes:
            raise SceneSpecError(f"{where}.nodes", "a non-empty array")
        nodes = nodes[:MAX_NODES]  # truncate rather than reject
        seen: dict[str, str] = {}
        parsed_nodes: list[tuple[str, str]] = []
        for nn, n in enumerate(nodes):
            if not isinstance(n, dict):
                continue  # drop a malformed node
            nid = n.get("id")
            if not isinstance(nid, str) or not _ID_RE.match(nid):
                continue  # drop a node with no usable id
            if nid in seen:
                continue  # de-dup, keeping the first
            label = _celltext(n.get("label"), f"{where}.nodes[{nn}].label", cap=48)
            seen[nid] = label
            parsed_nodes.append((nid, label))
        if not parsed_nodes:
            raise SceneSpecError(f"{where}.nodes", "no renderable node")
        edges = el.get("edges")
        edges = edges[:MAX_EDGES] if isinstance(edges, list) else []
        parsed_edges: list[tuple[str, str, str]] = []
        for en, e in enumerate(edges):
            if not isinstance(e, dict):
                continue  # drop a malformed edge
            a, b = e.get("from"), e.get("to")
            if a not in seen or b not in seen:
                continue  # drop an edge to an undeclared node
            lbl = e.get("label")
            lf = f"{where}.edges[{en}].label"
            elabel = _celltext(lbl, lf, cap=32) if lbl not in (None, "") else ""
            parsed_edges.append((a, b, elabel))
        return _render_links(parsed_nodes, parsed_edges)

    if kind == "tree":
        nodes = el.get("nodes")
        if not isinstance(nodes, list) or not nodes:
            raise SceneSpecError(f"{where}.nodes", "a non-empty array")
        nodes = nodes[:MAX_ROWS]  # truncate rather than reject
        byid: dict[str, dict[str, Any]] = {}
        order: list[str] = []
        for nn, n in enumerate(nodes):
            if not isinstance(n, dict):
                continue  # drop a malformed node
            nid = n.get("id")
            if not isinstance(nid, str) or not _ID_RE.match(nid):
                continue  # drop a node with no usable id
            if nid in byid:
                continue  # de-dup, keeping the first
            label = _celltext(n.get("label"), f"{where}.nodes[{nn}].label", cap=64)
            note = n.get("note")
            nf = f"{where}.nodes[{nn}].note"
            note_s = _celltext(note, nf, cap=64) if note not in (None, "") else ""
            parent = n.get("parent")
            if not isinstance(parent, str) or not parent:
                parent = None
            byid[nid] = {"label": label, "note": note_s, "parent": parent, "children": []}
            order.append(nid)
        if not byid:
            raise SceneSpecError(f"{where}.nodes", "no renderable node")
        # An undeclared parent is treated as a root rather than a fatal error.
        roots: list[str] = []
        for nid in order:
            parent = byid[nid]["parent"]
            if parent is None or parent not in byid:
                byid[nid]["parent"] = None
                roots.append(nid)
            else:
                byid[parent]["children"].append(nid)
        # No root at all (every node points at another — a cycle): promote the first.
        if not roots:
            first = order[0]
            byid[first]["parent"] = None
            for k in byid:
                if first in byid[k]["children"]:
                    byid[k]["children"].remove(first)
            roots.append(first)
        visited: set[str] = set()

        def _branch(nid: str, depth: int) -> str:
            # A back-edge or an over-deep branch is dropped, not fatal.
            if nid in visited or depth > MAX_TREE_DEPTH:
                return ""
            visited.add(nid)
            node = byid[nid]
            note_html = f' <span class="tn">{_esc(node["note"])}</span>' if node["note"] else ""
            inner = f"{_esc(node['label'])}{note_html}"
            kids = "".join(_branch(k, depth + 1) for k in node["children"])
            if kids:
                inner += "<ul>" + kids + "</ul>"
            return f"<li>{inner}</li>"

        branches = "".join(_branch(r, 0) for r in roots)
        # Any node still unreached (stranded by a cycle) is promoted as its own root.
        for nid in order:
            if nid not in visited:
                branches += _branch(nid, 0)
        return '<ul class="tree">' + branches + "</ul>"

    # choice
    cid = el.get("id")
    if not isinstance(cid, str) or not _ID_RE.match(cid):
        raise SceneSpecError(f"{where}.id", "a slug (a-z, 0-9, hyphen)")
    label = _esc(_text(el.get("label"), f"{where}.label"))
    # The id rides in a data attribute, never in generated script.
    return f'<button type="button" data-choice="{_esc(cid)}">{label}</button>'


def _render_links(nodes: list[tuple[str, str]], edges: list[tuple[str, str, str]]) -> str:
    """A relationship graph as inline SVG, laid out by the backend on a ring.

    The narrator supplies nodes and edges and NEVER a coordinate — every x/y here
    is computed from the node's ring position, so this stays inside the same trust
    boundary as the rest of the compiler: structure from the narrator, geometry
    from the app. Labels are the only narrator strings and each is escaped."""
    import math

    n = len(nodes)
    w, h = 320.0, 220.0
    cx, cy = w / 2, h / 2
    radius = min(w, h) / 2 - 34
    pos: dict[str, tuple[float, float]] = {}
    for i, (nid, _label) in enumerate(nodes):
        # A lone node sits at the centre; otherwise evenly spaced from the top.
        if n == 1:
            pos[nid] = (cx, cy)
        else:
            ang = -math.pi / 2 + 2 * math.pi * i / n
            pos[nid] = (cx + radius * math.cos(ang), cy + radius * math.sin(ang))
    parts = [f'<svg class="lk" viewBox="0 0 {w:.0f} {h:.0f}" role="img">']
    for a, b, lbl in edges:  # edges first, so nodes draw on top
        x1, y1 = pos[a]
        x2, y2 = pos[b]
        parts.append(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" class="lke"/>')
        if lbl:
            parts.append(
                f'<text x="{(x1 + x2) / 2:.1f}" y="{(y1 + y2) / 2:.1f}" class="lkl">{_esc(lbl)}</text>'
            )
    for nid, label in nodes:
        x, y = pos[nid]
        parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="5" class="lkn"/>')
        parts.append(f'<text x="{x:.1f}" y="{y - 9:.1f}" class="lknt">{_esc(label)}</text>')
    parts.append("</svg>")
    return '<div class="lkwrap">' + "".join(parts) + "</div>"


def _compile_scene(
    scene_id: str, spec: dict[str, Any], state: dict[str, Any], *, nonce: str = ""
) -> tuple[str, list[dict[str, Any]]]:
    """The salvaging core: ``(html, dropped)``.

    The WHOLE-spec gates (id, byte ceiling, markup ban, non-empty elements) are the
    trust boundary and stay hard — they raise. Per-ELEMENT faults are soft: a bad
    element is dropped, recorded in ``dropped``, and the rest render, because a
    legible partial scene beats a blank frame. Every string is still HTML-escaped.
    """
    if not isinstance(scene_id, str) or not _ID_RE.match(scene_id):
        raise SceneSpecError("sceneId", "a slug (a-z, 0-9, hyphen)")
    if not isinstance(spec, dict):
        raise SceneSpecError("spec", "an object")

    size = len(json.dumps(spec, ensure_ascii=False).encode("utf-8"))
    if size > MAX_SPEC_BYTES:
        raise SceneSpecError("spec", f"at most {MAX_SPEC_BYTES} bytes, got {size}")

    for banned in ("html", "innerHTML", "script", "srcdoc", "style"):
        if banned in spec:
            raise SceneSpecError(f"spec.{banned}", "a scene is described, not written")

    elements = spec.get("elements")
    if not isinstance(elements, list) or not elements:
        raise SceneSpecError("spec.elements", "a non-empty array")
    elements = elements[:MAX_ELEMENTS]  # truncate rather than reject the whole scene

    title = _text(spec.get("title"), "spec.title", cap=120)

    dropped: list[dict[str, Any]] = []
    parts: list[str] = []
    for i, el in enumerate(elements):
        try:
            parts.append(_element(el, i, state))
        except SceneSpecError as exc:
            # One bad element is skipped, not fatal — its loss is recorded so the
            # narrator can be told, but the scene still mounts and renders.
            dropped.append({"index": i, "field": exc.field, "reason": exc.expected})
    body = "".join(parts)

    # The CSP meta is the FIRST thing in <head>, ahead of every generated byte: a
    # policy that arrives after the content it governs has already lost.
    html_out = (
        '<!DOCTYPE html><html lang="zh" data-scene="'
        + _esc(scene_id)
        + '"'
        + ' data-nonce="'
        + _esc(nonce)
        + '"><head>'
        '<meta charset="utf-8">'
        f'<meta http-equiv="Content-Security-Policy" content="{CSP}">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        f"{_STYLE}</head><body>"
        + (f"<h3>{_esc(title)}</h3>" if title else "")
        + body
        + SCENE_SCRIPT
        + "</body></html>"
    )
    return html_out, dropped


def compile_scene(
    scene_id: str, spec: dict[str, Any], state: dict[str, Any], *, nonce: str = ""
) -> str:
    """A spec plus run state becomes one self-contained document.

    Fail-soft per element: one bad element is dropped and the rest render, so a
    single typo never turns the whole scene into a blank box. The whole-spec gates
    (markup ban, byte ceiling, empty elements) stay hard. Use ``scene_warnings`` to
    learn what was dropped so the narrator can fix it on its next turn.
    """
    html_out, _dropped = _compile_scene(scene_id, spec, state, nonce=nonce)
    return html_out


def scene_warnings(
    scene_id: str, spec: dict[str, Any], state: dict[str, Any], *, nonce: str = ""
) -> list[dict[str, Any]]:
    """The dropped-element records for a spec — never raises.

    The mount/update tools return this so the narrator learns what would not
    render. A whole-spec hard gate (markup / size / empty) surfaces as one warning
    (index ``-1``) rather than an exception, so the mount itself still succeeds.
    """
    try:
        _html, dropped = _compile_scene(scene_id, spec, state, nonce=nonce)
        return dropped
    except SceneSpecError as exc:
        return [{"index": -1, "field": exc.field, "reason": exc.expected}]


# ── caching, per run ────────────────────────────────────────────────────


def spec_digest(spec: dict[str, Any], state_slice: Any = None) -> str:
    """Identity of a compiled scene: the spec plus the compiler that made it.

    ``state_slice`` participates because a bound scene showing last month's
    numbers is exactly the drift this module exists to prevent — a cache hit must
    mean "the same picture", not "the same description".
    """
    payload = json.dumps(
        {"c": COMPILER, "spec": spec, "s": state_slice},
        ensure_ascii=False,
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def bound_values(spec: dict[str, Any], state: dict[str, Any]) -> dict[str, Any]:
    """Every value this spec binds, read from state.

    Derived from the spec rather than passed in, so the cache key and the render
    can never disagree about which paths matter. An unresolvable path contributes
    a sentinel instead of raising: this runs to build a KEY, and the real refusal
    belongs to the compile pass where the field can be named.
    """
    out: dict[str, Any] = {}
    for el in spec.get("elements") or []:
        if not isinstance(el, dict):
            continue
        path = el.get("bind")
        if not isinstance(path, str):
            continue
        try:
            out[path] = resolve_bind(path, state)
        except SceneSpecError:
            out[path] = "\u0000unresolved"
    return out


def widget_path(data_dir: Path, run_id: str, scene_id: str) -> Path:
    """Compiled HTML lives under the RUN, never the world.

    Specs travel between players; compiled bytes do not. Keeping them here is
    what makes "widget bytes are always locally produced" true even for a world
    pack that came from someone else.
    """
    if not _ID_RE.match(run_id) or not _ID_RE.match(scene_id):
        raise SceneSpecError("path", "a slug run id and scene id")
    return data_dir / "runs" / run_id / "widgets" / f"{scene_id}.html"


def compile_cached(
    data_dir: Path,
    run_id: str,
    scene_id: str,
    spec: dict[str, Any],
    state: dict[str, Any],
    *,
    bound_slice: Any = None,
    nonce: str = "",
) -> tuple[str, bool]:
    """``(html, from_cache)``. Recompiles whenever the digest moves."""
    # The nonce participates: a remount issues a new one, and a cached file
    # carrying the old one would let a replaced scene answer for its successor.
    digest = spec_digest(spec, {"b": bound_slice, "n": nonce})
    target = widget_path(data_dir, run_id, scene_id)
    marker = target.with_suffix(".sha256")

    if target.is_file() and marker.is_file():
        try:
            if marker.read_text(encoding="utf-8").strip() == digest:
                return target.read_text(encoding="utf-8"), True
        except OSError:
            pass  # unreadable cache is a cache miss, never a failure

    out = compile_scene(scene_id, spec, state, nonce=nonce)
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".html.tmp")
    tmp.write_text(out, encoding="utf-8")
    os.replace(tmp, target)
    marker.write_text(digest, encoding="utf-8")
    return out, False
