"""The scene compiler — a declared spec becomes HTML the app wrote.

The trust boundary of this whole app lives in this file. A narrator describes what
a scene should show; it never supplies markup. Everything below follows from that:

* **Element kinds are a closed set.** The narrator picks from templates; it cannot
  name a tag. An unknown kind is refused before anything mounts, because a
  compiler that skipped what it did not understand would let a spec fail open.
* **Every narrator string is escaped as text.** Narrator bytes reach the DOM only
  as content, never as markup or as script.
* **The one script is a constant.** It is emitted byte-identically and carries no
  interpolation. That is what makes ``script-src 'unsafe-inline'`` defensible: the
  inline script is the app's, and a test asserts the constant is what ships.
* **The CSP meta precedes every generated byte.** A policy that arrives after the
  content it governs has already lost.
* **``bind`` paths are resolved here, against run state.** A widget showing a
  number the panels disagree with is worse than no widget, and resolving in the
  page would put a second reader of state next to the first.

What the CSP allows, and why each entry is the narrowest form that still works:
``default-src 'none'`` (nothing loads), ``script-src 'unsafe-inline'`` (the app's
own constant, so a click can reach the parent), ``style-src 'unsafe-inline'`` (one
inline sheet), ``img-src data:`` (inline only — no network fetch dressed as an
image), ``connect-src 'none'`` (no exfiltration path at all), ``form-action
'none'`` and ``base-uri 'none'`` (no navigation-shaped escape).
"""

from __future__ import annotations

import hashlib
import html
import json
import os
import re
from pathlib import Path
from typing import Any

from view import strip_terminal_framing

#: Bumped when the compiled shape changes in a way a cached file cannot satisfy.
COMPILER = 1

#: A spec is a description, not a document. Anything past this is a narrator
#: trying to write a page.
MAX_SPEC_BYTES = 24_000
MAX_ELEMENTS = 60
MAX_TEXT = 400
MAX_ROWS = 40
MAX_COLUMNS = 6

#: The closed set. A kind absent here is refused, never skipped.
ELEMENT_KINDS: frozenset[str] = frozenset(
    {"heading", "text", "note", "stat", "bar", "keyvalue", "list", "table", "choice", "divider"}
)

_ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,63}$")
_PATH_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*$")


class SceneSpecError(ValueError):
    """A spec that cannot become a scene. Names the field so the narrator can fix
    the one thing that was wrong."""

    def __init__(self, field: str, expected: str) -> None:
        super().__init__(f"{field}: {expected}")
        self.field = field
        self.expected = expected


# ── the policy, and the one script ──────────────────────────────────────

CSP = (
    "default-src 'none'; "
    "script-src 'unsafe-inline'; "
    "style-src 'unsafe-inline'; "
    "img-src data:; "
    "connect-src 'none'; "
    "form-action 'none'; "
    "base-uri 'none'"
)

#: Emitted byte-identically, every time, with nothing interpolated into it. A
#: test asserts that: the moment narrator text could reach script context, the
#: escaping above stops being the boundary it claims to be.
#:
#: It reads a choice's id from a data attribute rather than from generated code,
#: and posts it to the parent. The parent side is the app's own frame host.
SCENE_SCRIPT = """<script>
(function () {
  document.addEventListener('click', function (e) {
    var el = e.target.closest('[data-choice]');
    if (!el) return;
    parent.postMessage({
      source: 'endless-scene',
      sceneId: document.documentElement.dataset.scene || '',
      nonce: document.documentElement.dataset.nonce || '',
      choice: el.dataset.choice
    }, '*');
  });
})();
</script>"""

_STYLE = """<style>
:root { color-scheme: dark light; }
body {
  margin: 0; padding: 12px;
  font: 13px/1.6 system-ui, -apple-system, "Segoe UI", sans-serif;
  color: #e2e8f0; background: transparent;
}
h3 { margin: 0 0 8px; font-size: 15px; font-weight: 600; }
.r { display: flex; gap: 10px; padding: 4px 0; align-items: baseline; }
.k { color: #6b7280; flex: 0 0 6em; }
.v { flex: 1; min-width: 0; overflow-wrap: anywhere; }
.n { color: #6b7280; }
.t { border-radius: 2px; height: 4px; background: #2d2f3d; margin-top: 5px; }
.f { height: 100%; background: #7c3aed; }
ul { margin: 6px 0; padding-left: 1.3em; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 4px 6px; border-bottom: 1px solid #2d2f3d; }
th { color: #6b7280; font-weight: 500; }
hr { border: none; border-top: 1px solid #2d2f3d; margin: 10px 0; }
button {
  display: block; width: 100%; text-align: left; margin: 6px 0;
  padding: 10px 12px; min-height: 44px;
  font: inherit; color: inherit; cursor: pointer;
  background: #1f2030; border: 1px solid #2d2f3d; border-radius: 8px;
}
</style>"""


# ── binding ──────────────────────────────────────────────────────────────


def resolve_bind(path: str, state: dict[str, Any]) -> Any:
    """Read a dotted path out of run state, or raise.

    Unresolvable is an ERROR here rather than a blank, unlike a panel's missing
    field. A panel gap is a fact the narrator has not mentioned yet; a scene bind
    is the narrator asserting a number exists and asking for it to be drawn, so
    a silent blank would ship a widget that quietly disagrees with the panels.
    """
    if not isinstance(path, str) or not _PATH_RE.match(path):
        raise SceneSpecError("bind", f"a dotted path, got {path!r}")
    node: Any = state
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            raise SceneSpecError("bind", f"nothing at {path!r}")
        node = node[part]
    return node


# ── compiling ────────────────────────────────────────────────────────────


def _text(value: Any, field: str, *, cap: int = MAX_TEXT) -> str:
    if value is None:
        return ""
    if not isinstance(value, (str, int, float)) or isinstance(value, bool):
        raise SceneSpecError(field, "text")
    out = str(value)
    if len(out) > cap:
        raise SceneSpecError(field, f"at most {cap} characters, got {len(out)}")
    return out


def _esc(value: Any) -> str:
    """Every narrator string passes through here on its way to the DOM.

    Escaping AND framing removal, in that order, because a scene is a second
    route to the DOM and R18 applies to both. Reusing the prose stripper rather
    than writing a second one: two implementations of "what counts as framing"
    would drift, and the one in ``view`` is the one with the tests that prove it
    keeps the words inside a box.
    """
    return html.escape(strip_terminal_framing(str(value)), quote=True)


def _pct(value: Any, cap: Any) -> float | None:
    try:
        v, c = float(value), float(cap)
    except (TypeError, ValueError):
        return None
    if c <= 0:
        return None
    return max(0.0, min(1.0, v / c))


def _element(el: Any, index: int, state: dict[str, Any]) -> str:
    where = f"elements[{index}]"
    if not isinstance(el, dict):
        raise SceneSpecError(where, "an object")
    kind = el.get("kind")
    if kind not in ELEMENT_KINDS:
        raise SceneSpecError(
            f"{where}.kind", f"one of {sorted(ELEMENT_KINDS)}, got {kind!r}"
        )

    # A bound value replaces `value`/`text` wherever an element takes one.
    bound: Any = None
    if "bind" in el:
        try:
            bound = resolve_bind(el["bind"], state)
        except SceneSpecError as exc:
            raise SceneSpecError(f"{where}.bind", exc.expected) from exc

    if kind == "divider":
        return "<hr>"

    if kind == "heading":
        return f"<h3>{_esc(_text(el.get('text'), f'{where}.text'))}</h3>"

    if kind in ("text", "note"):
        body = _esc(_text(bound if bound is not None else el.get("text"), f"{where}.text"))
        return f'<p class="n">{body}</p>' if kind == "note" else f"<p>{body}</p>"

    if kind == "keyvalue":
        label = _esc(_text(el.get("label"), f"{where}.label"))
        value = _esc(_text(bound if bound is not None else el.get("value"), f"{where}.value"))
        return f'<div class="r"><div class="k">{label}</div><div class="v">{value}</div></div>'

    if kind in ("stat", "bar"):
        label = _esc(_text(el.get("label"), f"{where}.label"))
        raw = bound if bound is not None else el.get("value")
        value = _esc(_text(raw, f"{where}.value", cap=64))
        cap = el.get("max")
        pct = _pct(raw, cap) if cap is not None else None
        tail = f'<span class="n"> / {_esc(_text(cap, f"{where}.max", cap=32))}</span>' if cap is not None else ""
        bar = f'<div class="t"><div class="f" style="width:{round(pct * 100)}%"></div></div>' if pct is not None else ""
        return (
            f'<div class="r"><div class="k">{label}</div>'
            f'<div class="v">{value}{tail}{bar}</div></div>'
        )

    if kind == "list":
        items = el.get("items")
        if not isinstance(items, list):
            raise SceneSpecError(f"{where}.items", "an array")
        if len(items) > MAX_ROWS:
            raise SceneSpecError(f"{where}.items", f"at most {MAX_ROWS} entries")
        cells = "".join(
            f"<li>{_esc(_text(i, f'{where}.items[{n}]'))}</li>" for n, i in enumerate(items)
        )
        return f"<ul>{cells}</ul>"

    if kind == "table":
        cols = el.get("columns")
        rows = el.get("rows")
        if not isinstance(cols, list) or not cols:
            raise SceneSpecError(f"{where}.columns", "a non-empty array")
        if len(cols) > MAX_COLUMNS:
            raise SceneSpecError(f"{where}.columns", f"at most {MAX_COLUMNS}")
        if not isinstance(rows, list):
            raise SceneSpecError(f"{where}.rows", "an array")
        if len(rows) > MAX_ROWS:
            raise SceneSpecError(f"{where}.rows", f"at most {MAX_ROWS} rows")
        head = "".join(
            f"<th>{_esc(_text(c, f'{where}.columns[{n}]'))}</th>" for n, c in enumerate(cols)
        )
        body = ""
        for rn, row in enumerate(rows):
            if not isinstance(row, list):
                raise SceneSpecError(f"{where}.rows[{rn}]", "an array")
            if len(row) != len(cols):
                raise SceneSpecError(
                    f"{where}.rows[{rn}]", f"{len(cols)} cells, got {len(row)}"
                )
            body += "<tr>" + "".join(
                f"<td>{_esc(_text(c, f'{where}.rows[{rn}][{cn}]'))}</td>"
                for cn, c in enumerate(row)
            ) + "</tr>"
        return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"

    # choice
    cid = el.get("id")
    if not isinstance(cid, str) or not _ID_RE.match(cid):
        raise SceneSpecError(f"{where}.id", "a slug (a-z, 0-9, hyphen)")
    label = _esc(_text(el.get("label"), f"{where}.label"))
    # The id rides in a data attribute, never in generated script.
    return f'<button type="button" data-choice="{_esc(cid)}">{label}</button>'


def compile_scene(
    scene_id: str, spec: dict[str, Any], state: dict[str, Any], *, nonce: str = ""
) -> str:
    """A spec plus run state becomes one self-contained document.

    Validates the WHOLE spec before emitting anything, so a scene never mounts
    half-drawn: a widget missing its second half looks to the player like the
    world forgetting what it was saying.
    """
    if not isinstance(scene_id, str) or not _ID_RE.match(scene_id):
        raise SceneSpecError("sceneId", "a slug (a-z, 0-9, hyphen)")
    if not isinstance(spec, dict):
        raise SceneSpecError("spec", "an object")

    size = len(json.dumps(spec, ensure_ascii=False).encode("utf-8"))
    if size > MAX_SPEC_BYTES:
        raise SceneSpecError("spec", f"at most {MAX_SPEC_BYTES} bytes, got {size}")

    for banned in ("html", "innerHTML", "script", "srcdoc", "style"):
        if banned in spec:
            raise SceneSpecError(f"spec.{banned}", "a scene is described, not written")

    elements = spec.get("elements")
    if not isinstance(elements, list) or not elements:
        raise SceneSpecError("spec.elements", "a non-empty array")
    if len(elements) > MAX_ELEMENTS:
        raise SceneSpecError("spec.elements", f"at most {MAX_ELEMENTS}, got {len(elements)}")

    title = _text(spec.get("title"), "spec.title", cap=120)
    body = "".join(_element(el, i, state) for i, el in enumerate(elements))

    # The CSP meta is the FIRST thing in <head>, ahead of every generated byte: a
    # policy that arrives after the content it governs has already lost.
    return (
        "<!DOCTYPE html><html lang=\"zh\" data-scene=\"" + _esc(scene_id) + "\""
        + " data-nonce=\"" + _esc(nonce) + "\"><head>"
        '<meta charset="utf-8">'
        f'<meta http-equiv="Content-Security-Policy" content="{CSP}">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        f"{_STYLE}</head><body>"
        + (f"<h3>{_esc(title)}</h3>" if title else "")
        + body
        + SCENE_SCRIPT
        + "</body></html>"
    )


# ── caching, per run ────────────────────────────────────────────────────


def spec_digest(spec: dict[str, Any], state_slice: Any = None) -> str:
    """Identity of a compiled scene: the spec plus the compiler that made it.

    ``state_slice`` participates because a bound scene showing last month's
    numbers is exactly the drift this module exists to prevent — a cache hit must
    mean "the same picture", not "the same description".
    """
    payload = json.dumps(
        {"c": COMPILER, "spec": spec, "s": state_slice},
        ensure_ascii=False, sort_keys=True,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def bound_values(spec: dict[str, Any], state: dict[str, Any]) -> dict[str, Any]:
    """Every value this spec binds, read from state.

    Derived from the spec rather than passed in, so the cache key and the render
    can never disagree about which paths matter. An unresolvable path contributes
    a sentinel instead of raising: this runs to build a KEY, and the real refusal
    belongs to the compile pass where the field can be named.
    """
    out: dict[str, Any] = {}
    for el in spec.get("elements") or []:
        if not isinstance(el, dict):
            continue
        path = el.get("bind")
        if not isinstance(path, str):
            continue
        try:
            out[path] = resolve_bind(path, state)
        except SceneSpecError:
            out[path] = "\u0000unresolved"
    return out


def widget_path(data_dir: Path, run_id: str, scene_id: str) -> Path:
    """Compiled HTML lives under the RUN, never the world.

    Specs travel between players; compiled bytes do not. Keeping them here is
    what makes "widget bytes are always locally produced" true even for a world
    pack that came from someone else.
    """
    if not _ID_RE.match(run_id) or not _ID_RE.match(scene_id):
        raise SceneSpecError("path", "a slug run id and scene id")
    return data_dir / "runs" / run_id / "widgets" / f"{scene_id}.html"


def compile_cached(
    data_dir: Path,
    run_id: str,
    scene_id: str,
    spec: dict[str, Any],
    state: dict[str, Any],
    *,
    bound_slice: Any = None,
    nonce: str = "",
) -> tuple[str, bool]:
    """``(html, from_cache)``. Recompiles whenever the digest moves."""
    # The nonce participates: a remount issues a new one, and a cached file
    # carrying the old one would let a replaced scene answer for its successor.
    digest = spec_digest(spec, {"b": bound_slice, "n": nonce})
    target = widget_path(data_dir, run_id, scene_id)
    marker = target.with_suffix(".sha256")

    if target.is_file() and marker.is_file():
        try:
            if marker.read_text(encoding="utf-8").strip() == digest:
                return target.read_text(encoding="utf-8"), True
        except OSError:
            pass  # unreadable cache is a cache miss, never a failure

    out = compile_scene(scene_id, spec, state, nonce=nonce)
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".html.tmp")
    tmp.write_text(out, encoding="utf-8")
    os.replace(tmp, target)
    marker.write_text(digest, encoding="utf-8")
    return out, False
